import argparse
parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--U_spa',type=int,default=1, help='')
parser.add_argument('--U_spc',type=int,default=1, help='')
parser.add_argument('--pretrain',type=int,default=1, help='')
parser.add_argument('--lr_dc',type=float,default=1.1e-4 , help='')
parser.add_argument('--lr_da',type=float,default=1.1e-4 , help='')
parser.add_argument('--lr_i',type=float,default=1.2e-3, help='')
parser.add_argument('--kers',type=int,default=1, help='')
parser.add_argument('--N_h',type=int,default=40, help='')
parser.add_argument('--N_m',type=int,default=40, help='')
parser.add_argument('--sf', type=int, default=32, help='scale factor')
parser.add_argument('--msi_channel', type=int, default=4)
parser.add_argument('--hsi_channel', type=int, default=128)
parser.add_argument('--max_epoch', type=int, default=5000)
opt=parser.parse_args()
